version: '3.7'
services:
  web:
    image: rundeck/rundeck:3.0.23
    ports:
    - 4440:4440
    volumes:
    - rundeck-data-vol:/home/rundeck/server/data
    - rundeck-node-def-vol:/home/rundeck/demo-ops-nodes
    - rundeck-ssh-vol:/home/rundeck/.ssh
    - /home/ftravaglia/work/docker/rundeck/libext:/home/rundeck/libext
    extra_hosts:
    - vmi-local-1:192.168.56.101
    - vmi-local-2:192.168.56.102
    - vmi-local-3:192.168.56.103
    - rundeck.localhost:172.17.0.1
    - rocketchat.localhost:172.17.0.1
  bdd:
    image: postgres:9
    ports:
    - 5432:5432
    volumes:
    - rundeck-pg-vol:/var/lib/postgresql/data
    environment:
    - POSTGRES_PASSWORD=rundeck
    - POSTGRES_USER=rundeck    
    - POSTGRES_DB=rundeck
volumes:

  rundeck-ssh-vol: 
    external: true
    name: rundeck-ssh-vol
  rundeck-pg-vol: 
    external: true
    name: rundeck-pg-vol
  rundeck-node-def-vol: 
    external: true
    name: rundeck-node-def-vol
  rundeck-data-vol: 
    external: true
    name: rundeck-data-vol
  rundeck-plugin-vol:
    external: true
    name: rundeck-plugin-vol
